//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COPYPROv2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COPYPROv2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACEPTAR.
        /// </summary>
        internal static string AcceptButtonText {
            get {
                return ResourceManager.GetString("AcceptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo Pdf (.pdf) |*.pdf.
        /// </summary>
        internal static string ArchivoPdfFilter {
            get {
                return ResourceManager.GetString("ArchivoPdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de texto (*.txt)|*.txt.
        /// </summary>
        internal static string ArchivosDeTextoFilter {
            get {
                return ResourceManager.GetString("ArchivosDeTextoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportación exitosa!.
        /// </summary>
        internal static string ExportacionExitosa {
            get {
                return ResourceManager.GetString("ExportacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar a Pdf.
        /// </summary>
        internal static string ExportarPdfTitle {
            get {
                return ResourceManager.GetString("ExportarPdfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPYPRO v3
        ///
        ///INSTRUCCIONES DE USO: 
        ///Localice la informacion que desea escribir desde un archivo, pagina web, u otro programa, a continuación abra el programa COPYPRO y escriba dentro de la caja de texto y al final de clic en el boton exportar a un archivo de texto a su escritorio.
        ///Al presionar el boton ExportarTXT se crea un archivo de texto multiple con el historial del contenido de la caja de texto.
        ///Puede dar clic en el boton limpiar para borrar todo el contenido de la caja de texto.
        ///COPYPRO: es un p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I N F O R M A C I O N.
        /// </summary>
        internal static string InfoTitulo {
            get {
                return ResourceManager.GetString("InfoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAJE.
        /// </summary>
        internal static string MensajeTitulo {
            get {
                return ResourceManager.GetString("MensajeTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Va a salir del programa, vuelva pronto!.
        /// </summary>
        internal static string MensajeVuelvaPronto {
            get {
                return ResourceManager.GetString("MensajeVuelvaPronto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un archivo de texto.
        /// </summary>
        internal static string SeleccioneArchivoDeTexto {
            get {
                return ResourceManager.GetString("SeleccioneArchivoDeTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apertura de archivo de texto..
        /// </summary>
        internal static string TituloAbrirArchivoDeTexto {
            get {
                return ResourceManager.GetString("TituloAbrirArchivoDeTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Archivo de Texto.
        /// </summary>
        internal static string TituloGuardarArchivoDeTexto {
            get {
                return ResourceManager.GetString("TituloGuardarArchivoDeTexto", resourceCulture);
            }
        }
    }
}
